apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fake-library
  description: A totally fake librarytry
  tags:
    - python
  links:
    - url: https://dashboard.example.com
      title: Documentation
      icon: docs
spec:
  type: library
  lifecycle: experimental
  owner: user:default/guest
